name: OWASP Zap Scan

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "14.15"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Serve
        run: npm run serve

  pentest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: OWASP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "localhost:5000"
