name: OWASP Zap Scan

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          repository: pgp-image
          tags: user/app:latest
      - uses: addnab/docker-run-action@v3
        with:
          image: pgp-image:latest
          run: docker run -d  --rm -p 5000:5000 pgp-image:latest

  pentest:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: OWASP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "localhost:5000"
